// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAx8PnuPvv_gfckbQUTz0MnZrrDS-iQj74',
    appId: '1:264130129228:web:bb7b3dbdf610889913f3e9',
    messagingSenderId: '264130129228',
    projectId: 'oceanic-hook-448911-m7',
    authDomain: 'oceanic-hook-448911-m7.firebaseapp.com',
    storageBucket: 'oceanic-hook-448911-m7.firebasestorage.app',
    measurementId: 'G-JZ5G3KLCDB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7VJHIA6R0YzG8Ba9IRrhGEqXHXFPDFeg',
    appId: '1:264130129228:android:1d337daac838dce513f3e9',
    messagingSenderId: '264130129228',
    projectId: 'oceanic-hook-448911-m7',
    storageBucket: 'oceanic-hook-448911-m7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAXHsIobCGwMt3UEB5FZ53mrP6hcW1na0',
    appId: '1:264130129228:ios:c7d84d156b41f59d13f3e9',
    messagingSenderId: '264130129228',
    projectId: 'oceanic-hook-448911-m7',
    storageBucket: 'oceanic-hook-448911-m7.firebasestorage.app',
    iosBundleId: 'com.example.randomUser',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAXHsIobCGwMt3UEB5FZ53mrP6hcW1na0',
    appId: '1:264130129228:ios:c7d84d156b41f59d13f3e9',
    messagingSenderId: '264130129228',
    projectId: 'oceanic-hook-448911-m7',
    storageBucket: 'oceanic-hook-448911-m7.firebasestorage.app',
    iosBundleId: 'com.example.randomUser',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAx8PnuPvv_gfckbQUTz0MnZrrDS-iQj74',
    appId: '1:264130129228:web:11a327d90b1c03db13f3e9',
    messagingSenderId: '264130129228',
    projectId: 'oceanic-hook-448911-m7',
    authDomain: 'oceanic-hook-448911-m7.firebaseapp.com',
    storageBucket: 'oceanic-hook-448911-m7.firebasestorage.app',
    measurementId: 'G-4XBV8DNMN4',
  );

}